### PR TITLE
Add support for passing json values to arguments as .txt files

### PR DESCRIPTION
**Pull request by Christina-Kang**
Changes include:

- Give users the option of passing in a .txt file where they have to pass in a json value for an argument.

Verifed:

- [ ] Build and test CI passes
- [ ] History and readme updated to reflect changes
- [ ] Package version updated according to semantic versioning rules
- [ ] Tests modified or added, when applicable
- [ ] Updated code owners file, when applicable
- [ ] Read the [PR checklist](https://github.com/Azure/service-fabric-cli/wiki/Checklist)

### CODE REVIEW

**Comment by samedder** [comment]
Is this something that Knack cannot support?

**Comment by samedder** [comment]
Rather than us writing custom logic for this, we should contribute to Knack or request them to support this. I don't think this is a feature that should only be added to our CLI.

**Comment by samedder** [comment]
If you've written all the code already for our CLI how much more effort would it be to migrate it back out to knack?

**Comment by Christina-Kang** [comment]
@samedder I would need to go through all their code and determine what is the best way of adding this without impacting existing items. Probably as a pre-defined built in type, then understand their testing framework which I have not looked at, then update docs, etc. I would need to discuss with their team if that's how they want it to be implemented. It's a non-trivial amount of work to port this. I can add a tracking item and get to it when I have time, but I doubt it will be this month.

**Comment by samedder** [comment]
@Christina-Kang two things:
1 - This sounds like it needs to be ported from Azure CLI, I'm fine merging this but we should push back and ask Knack to support the same feature set as Azure CLI
2 - Follow the same `@` convention to specify file names

**Pull request merged**
